// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCt8C8loBstG3whIrYYrsj5-zTSSe2ZOzs',
    appId: '1:640788715599:web:0a1f3fa5bfa4cb3d32b23a',
    messagingSenderId: '640788715599',
    projectId: 'glufri-app-project',
    authDomain: 'glufri-app-project.firebaseapp.com',
    storageBucket: 'glufri-app-project.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChK7V8KJrIvCYX88Nuv2kkNFbvhcn6Frc',
    appId: '1:640788715599:android:6b17e3f5d1da4b6e32b23a',
    messagingSenderId: '640788715599',
    projectId: 'glufri-app-project',
    storageBucket: 'glufri-app-project.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3sAN6zPZXYEM0OZzgV2sqEKOm6uOJYZE',
    appId: '1:640788715599:ios:88cfc3b40c06752932b23a',
    messagingSenderId: '640788715599',
    projectId: 'glufri-app-project',
    storageBucket: 'glufri-app-project.firebasestorage.app',
    iosBundleId: 'com.example.glufri',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC3sAN6zPZXYEM0OZzgV2sqEKOm6uOJYZE',
    appId: '1:640788715599:ios:88cfc3b40c06752932b23a',
    messagingSenderId: '640788715599',
    projectId: 'glufri-app-project',
    storageBucket: 'glufri-app-project.firebasestorage.app',
    iosBundleId: 'com.example.glufri',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCt8C8loBstG3whIrYYrsj5-zTSSe2ZOzs',
    appId: '1:640788715599:web:10cdc930bb12166d32b23a',
    messagingSenderId: '640788715599',
    projectId: 'glufri-app-project',
    authDomain: 'glufri-app-project.firebaseapp.com',
    storageBucket: 'glufri-app-project.firebasestorage.app',
  );
}
