// Mocks generated by Mockito 5.4.4 from annotations
// in glufri/test/features/purchase/presentation/providers/cart_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:glufri/features/purchase/data/models/purchase_model.dart'
    as _i4;
import 'package:glufri/features/purchase/domain/repositories/purchase_repository.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [PurchaseRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockPurchaseRepository extends _i1.Mock
    implements _i2.PurchaseRepository {
  @override
  _i3.Future<List<_i4.PurchaseModel>> getPurchases() => (super.noSuchMethod(
        Invocation.method(
          #getPurchases,
          [],
        ),
        returnValue:
            _i3.Future<List<_i4.PurchaseModel>>.value(<_i4.PurchaseModel>[]),
        returnValueForMissingStub:
            _i3.Future<List<_i4.PurchaseModel>>.value(<_i4.PurchaseModel>[]),
      ) as _i3.Future<List<_i4.PurchaseModel>>);

  @override
  _i3.Future<void> addPurchase(_i4.PurchaseModel? purchase) =>
      (super.noSuchMethod(
        Invocation.method(
          #addPurchase,
          [purchase],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> deletePurchase(String? purchaseId) => (super.noSuchMethod(
        Invocation.method(
          #deletePurchase,
          [purchaseId],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> updatePurchase(_i4.PurchaseModel? purchase) =>
      (super.noSuchMethod(
        Invocation.method(
          #updatePurchase,
          [purchase],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}
